---
sudo: required
language: generic

before_install:
  # Install pip
  - sudo easy_install pip
  - sudo pip install ansible
  - sudo pip install ansible-lint
  - sudo pip install yamllint

install:
  # Check versions
  - python --version
  - ansible --version
  - ansible-lint --version
  - yamllint --version

script:
  # Lint all YAML files.
  - yamllint .

  # Check the role/playbook's syntax.
  - ansible-playbook tests/playbook.yml --syntax-check

  # Lint the playbook.
  - ansible-lint tests/playbook.yml

  # Test the playbook.
  - ansible-playbook tests/playbook.yml

  # Test the playbook's idempotence.
  - idempotence=$(mktemp)
  - ansible-playbook tests/playbook.yml | tee -a ${idempotence}
  - >-
      tail -25 ${idempotence} |
      grep -q 'changed=1.*failed=0' &&
      (echo 'Idempotence test: pass' && exit 0) ||
      (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
